- name: agent configuration
  hosts: rocky
  become: yes
  tasks:
    - name: Import Wazuh GPG Key # This is to import the Wazuh GPG key - cannot pull wazuh agent package without it!
      rpm_key: 
        key: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
        state: present
    - name: Install Wazuh agent package
      yum:
        name: "https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.11-1.x86_64.rpm"
        state: present
      environment:
        WAZUH_MANAGER: "10.0.5.85"
        WAZUH_AGENT_GROUP: "default"
    - name: Allow port 1514, 1515, 55000 through firewalld
      shell: firewall-cmd --permanent --add-port=1514/tcp && firewall-cmd --permanent --add-port=1515/tcp && firewall-cmd --permanent --add-port=55000/tcp && firewall-cmd --reload
      become: yes
    - name: Enable and Start Wazuh Agent
      shell: systemctl start wazuh-agent
      become: yes
    - name: Bounce The Box
      shell: "sleep 5 && restart -r"
      become: yes
      async: 1
      poll: 0